// Study/VueJS/vue_basic/src/App.vue
<template>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <User />
            </div>
        </div>
    </div>
</template>

<script>
import User from './components/User';

export default {
    name: 'App',
    components: {
        User,
    },
};
</script>

<style>
div.component {
    border: 1px solid black;
    padding: 30px;
}
</style>

// Study/ReactJS/basic/src/App.js
import React, { Component } from 'react'
import Header from './components/Header.js'
import Product from './components/Product.js'
export default class App extends Component {
  render() {
    return (
      <div>
        
        <Header />
        
        <div className="row">
          <div className="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <Product />
          </div>
          <div className="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <Product />
          </div>
        </div>
        
        
      </div>
    )
  }
}
